# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  major: 0
  minor: 0
  patch: $(Build.BuildID)
  buildVer: $(major).$(minor).$(Build.BuildID)

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/Build/build.ps1'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack $(buildConfiguration)'
      inputs:
        command: pack
        versioningScheme: byPrereleaseNumber
        majorVersion: '$(Major)'
        minorVersion: '$(Minor)'
        patchVersion: '$(Patch)'



- stage: Test
  jobs:
  - job: B1

  
- stage: Deploy
  jobs:
  - job: B1